library(igraph)
library(igraphdata)
library(blockmodels)

source("csgc.R")

set.seed(2000)

fit.sbm = function(A, max.k=10) {
  message("----")
  message("blockmodels - BM_Bernoulli")
  
  sbm = BM_bernoulli("SBM_sym",A,verbosity=0, explore_min=max.k)
  sbm$estimate()

  message("Recommended no. of groups: ", which.max(sbm$ICL))
  
  for (k in 1:max.k) {
    
    mship = apply(sbm$memberships[[k]]$Z,1,which.max)
    K.hat = sbm$model_parameters[[k]]$pi

    message("----")
    message("Groups = ", k)
    
    print(csgc(A,K.hat[mship,mship])$z)
  }
  
  return(sbm)
}

message("------------------------------------------------------------")
message("Analysing graph generated by 4x4 SBM")

Ptrue = matrix(c(0.45, 0.34, 0.82, 0.60,
                 0.34, 0.70, 0.98, 0.57,
                 0.82, 0.98, 0.03, 0.82,
                 0.60, 0.57, 0.82, 0.25), 4, 4) / 2
A1 = as_adjacency_matrix(sbm.game(200, Ptrue, c(50,50,50,50)), sparse=FALSE)
m1 = fit.sbm(A1)

message("\n\n------------------------------------------------------------")
message("Analysing 'rfid' data")

data(rfid)
A2 = (as_adjacency_matrix(rfid,sparse=FALSE) > 0) * 1
m2 = fit.sbm(A2)



